services:
  backend:
    build: ./backend
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      POSTGRES_DATABASE_URL: ${POSTGRES_DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER:-lunisoft}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      APP_JWT_PRIVATE_KEY: ${APP_JWT_PRIVATE_KEY}
      APP_JWT_PUBLIC_KEY: ${APP_JWT_PUBLIC_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
