services:
  postgres:
    image: postgres:17.9
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-lunisoft}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_DB: ultimatejavastarterkit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lunisoft -d ultimatejavastarterkit" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.6.2-alpine
    volumes:
      - redis_data:/data

  caddy:
    image: lunisoft/terracapital:caddy
    build:
      context: ./caddy
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      frontend:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    image: lunisoft/terracapital:frontend
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
    healthcheck:
      test: "curl -s http://localhost:3000 || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: lunisoft/terracapital:backend
    build: ./backend
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      POSTGRES_DATABASE_URL: ${POSTGRES_DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER:-lunisoft}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      APP_JWT_PRIVATE_KEY: ${APP_JWT_PRIVATE_KEY}
      APP_JWT_PUBLIC_KEY: ${APP_JWT_PUBLIC_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:
