spring:
  application:
    name: java-starter
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${POSTGRES_DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${APP_REDIS_HOST}
      port: ${APP_REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50 # Batch the SELECT SQL queries automatically
        jdbc:
          batch_size: 50 # Batch the INSERT/UPDATE/DELETE SQL queries automatically
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.lunisoft: DEBUG
  file:
    name: logs/application.log        # or use `path:` to set a dir only
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
      file-name-pattern: logs/application-%d{yyyy-MM-dd}.%i.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health,info,loggers,logfile,metrics,env
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

jobrunr:
  background-job-server:
    enabled: true
  dashboard:
    enabled: true
    username: lunisoft
    password: ${APP_JOBRUNR_DASHBOARD_PASSWORD}

server:
  port: ${APP_PORT:3000}

app:
  jwt:
    private-key: ${APP_JWT_PRIVATE_KEY}
    public-key: ${APP_JWT_PUBLIC_KEY}
    issuer: lunisoft-java-starter
    audience: lunisoft-java-starter
    access-token-expiration-minutes: 15
    refresh-token-expiration-minutes: 44640
  cookie:
    secure: true
  cors:
    allowed-origins:
      - https://localhost
  storage:
    endpoint: ${APP_STORAGE_ENDPOINT}
    region: ${APP_STORAGE_REGION:auto}
    access-key: ${APP_STORAGE_ACCESS_KEY}
    secret-key: ${APP_STORAGE_SECRET_KEY}
    bucket: ${APP_STORAGE_BUCKET}
  email:
    brevo:
      api-key: ${APP_BREVO_API_KEY}
      sender-name: Java Starter
      sender-email: contact@lunisoft.fr
  pdf:
    render-timeout-ms: 10000
    format: A4
    print-background: true